name: Test
on: 
  [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: yarn
      - name: Check Solidity
        run: yarn compile-sol
      - name: Build
        run: yarn build
      - name: Check Links
        run: yarn linkcheck
