name: Test
on:
  [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Check Links
        run: yarn linkcheck
      - name: Check Solidity
        run: yarn test
