name: Test
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x]
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Setup Node
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8
        with:
          node-version: 18
          cache: 'npm'
      - name: Checkout Repo
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      - name: Install Dependencies
        run: npm i
      - name: Check Solidity Compilation
        run: npm run sol:compile
      - name: Check Solidity Solhint
        run: npm run lint-solc
      - name: Check Eslint
        run: npm run lint
      - name: Build
        run: npm run build
      # TODO: fix css files throwing 404 errors
      - name: Check internal links
        run: npm run linkcheck-internal